WITH
s0 AS (
  SELECT *,
    -- cut-off date is 29th march, 2026
  -- last day of FY25
  ABS(DATE_DIFF(DATE("2026-03-29"), `LATEST_ORDER_DATE`, DAY)) AS `RECENCY`
  FROM `filters`
),
s1 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_52W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `ORDER_ID`
  END AS `FREQUENCY_52W`
  FROM s0
),
s2 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_104W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `ORDER_ID`
  END AS `FREQUENCY_104W`
  FROM s1
),
s3 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_156W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `ORDER_ID`
  END AS `FREQUENCY_156W`
  FROM s2
),
s4 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_208W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `ORDER_ID`
  END AS `FREQUENCY_208W`
  FROM s3
),
s5 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_260W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `ORDER_ID`
  END AS `FREQUENCY_260W`
  FROM s4
),
s6 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_52W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_PAID_EXCL_TAX`
  END AS `MONETARY_52W`
  FROM s5
),
s7 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_104W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_PAID_EXCL_TAX`
  END AS `MONETARY_104W`
  FROM s6
),
s8 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_156W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_PAID_EXCL_TAX`
  END AS `MONETARY_156W`
  FROM s7
),
s9 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_208W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_PAID_EXCL_TAX`
  END AS `MONETARY_208W`
  FROM s8
),
s10 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_260W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_PAID_EXCL_TAX`
  END AS `MONETARY_260W`
  FROM s9
)
SELECT * FROM s10
