WITH
s0 AS (
  SELECT *,
    `DAYS_SINCE_PREVIOUS_ORDER` AS `DAYS_SINCE_PREVIOUS_ORDER_1`
  FROM `filters`
),
s1 AS (
  SELECT * EXCEPT (`CUSTOMER_ID`), `CUSTOMER_ID` AS `CUSTOMER_ID_REM`
  FROM s0
)
SELECT * FROM s1
