WITH
s0 AS (
  SELECT `CUSTOMER_ID`, `PRODUCT_CATEGORY`, `AMOUNT_PAID_EXCL_TAX`
  FROM `filters`
),
s1 AS (
  SELECT * EXCEPT (`PRODUCT_CATEGORY`),
    LOWER(`PRODUCT_CATEGORY`) AS `PRODUCT_CATEGORY`
  FROM s0
)
SELECT * FROM s1
