WITH
s0 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_13W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `ORDER_ID`
  END AS `ORDERS_13W`
  FROM `rfm`
),
s1 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_13W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_PAID_EXCL_TAX`
  END AS `DEMAND_13W`
  FROM s0
)
SELECT * FROM s1
