WITH
s0 AS (
  SELECT *,
    CASE
  WHEN COALESCE(`CUSTCOL_BB1_MARKED_DOWN`, CAST(`CURRENT_RETAIL_PRICE` AS STRING)) IS NULL = FALSE AND ((`TYPE` = "CreditMemo" AND (`AMOUNT_REFUNDED_INC_TAX` / `QUANTITY_RETURNED`) < `RRP`) OR (`TYPE` <> "CreditMemo" AND (`AMOUNT_PAID_INC_TAX` / `QUANTITY_SOLD`) < `RRP`)) THEN "Markdown"
  ELSE "Full Price"
  END AS `MARK_DOWN_STATUS`
  FROM `rfm`
),
s1 AS (
  SELECT `MARK_DOWN_STATUS`, `CUSTOMER_ID`, `AMOUNT_PAID_EXCL_TAX`
  FROM s0
)
SELECT * FROM s1
