SELECT
  `CUSTOMER_ID_REM`,
  `ORDER_ID`,
  MAX(`DAYS_SINCE_PREVIOUS_ORDER`) AS `DAYS_SINCE_PREVIOUS_ORDER`,
  MAX(`DAYS_SINCE_PREVIOUS_ORDER_1`) AS `DAYS_SINCE_PREVIOUS_ORDER_1`
FROM `dupe_days_since_last_purchase`
GROUP BY `CUSTOMER_ID_REM`, `ORDER_ID`
