WITH
s0 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_52W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_REFUNDED_EXCL_TAX`
  END AS `RETURNS_52W`
  FROM `recent_signals`
),
s1 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_104W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_REFUNDED_EXCL_TAX`
  END AS `RETURNS_104W`
  FROM s0
),
s2 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_156W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_REFUNDED_EXCL_TAX`
  END AS `RETURNS_156W`
  FROM s1
),
s3 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_208W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_REFUNDED_EXCL_TAX`
  END AS `RETURNS_208W`
  FROM s2
),
s4 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_260W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_REFUNDED_EXCL_TAX`
  END AS `RETURNS_260W`
  FROM s3
),
s5 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_13W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `AMOUNT_REFUNDED_EXCL_TAX`
  END AS `RETURNS_13W`
  FROM s4
)
SELECT * FROM s5
