WITH
s0 AS (
  SELECT *,
    CASE
  WHEN `CHANNEL_GROUP` = "Wholesale" AND `TYPE` = "Invoice" THEN `AMOUNT_PAID_EXCL_TAX` / `QUANTITY_SOLD`
  WHEN `CHANNEL_GROUP` = "Wholesale" AND `TYPE` = "CreditMemo" THEN `AMOUNT_REFUNDED_EXCL_TAX` / `QUANTITY_RETURNED`
  WHEN `REGION` <> "UK" THEN `RRP`
  ELSE (`RRP` / 120) * 100
  END AS `RRP_EXCL_TAX`
  FROM `returns`
),
s1 AS (
  SELECT *,
    CASE
  WHEN ((`RRP_EXCL_TAX` * `QUANTITY_SOLD`) - `AMOUNT_PAID_EXCL_TAX`) / `AMOUNT_PAID_EXCL_TAX` + ((`RRP_EXCL_TAX` * `QUANTITY_SOLD`) - `AMOUNT_PAID_EXCL_TAX`) < 0.075 THEN 0
  ELSE ((`RRP_EXCL_TAX` * `QUANTITY_SOLD`) - `AMOUNT_PAID_EXCL_TAX`)
  END AS `DISCOUNT_AMOUNT`
  FROM s0
),
s2 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_52W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `DISCOUNT_AMOUNT`
  END AS `DISCOUNT_52W`
  FROM s1
),
s3 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_104W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `DISCOUNT_AMOUNT`
  END AS `DISCOUNT_104W`
  FROM s2
),
s4 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_156W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `DISCOUNT_AMOUNT`
  END AS `DISCOUNT_156W`
  FROM s3
),
s5 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_208W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `DISCOUNT_AMOUNT`
  END AS `DISCOUNT_208W`
  FROM s4
),
s6 AS (
  SELECT *,
    CASE
  WHEN `DATE` >= `START_OF_ANALYSIS_PERIOD_260W` AND `DATE` <= `END_OF_ANALYSIS_PERIOD` THEN `DISCOUNT_AMOUNT`
  END AS `DISCOUNT_260W`
  FROM s5
)
SELECT * FROM s6
