SELECT
  `CUSTOMER_ID_REM`,
  AVG(`DAYS_SINCE_PREVIOUS_ORDER`) AS `DAYS_SINCE_PREVIOUS_ORDER`,
  STDDEV(`DAYS_SINCE_PREVIOUS_ORDER_1`) AS `DAYS_SINCE_PREVIOUS_ORDER_1`
FROM `remove_order_id`
GROUP BY `CUSTOMER_ID_REM`
