WITH
s0 AS (
  SELECT * EXCEPT (`BASE_LAYERS`), `BASE_LAYERS` AS `BASE_LAYERS`
  FROM `category_demand`
),
s1 AS (
  SELECT * EXCEPT (`DRESSES_AND_JUMPSUITS`), `DRESSES_AND_JUMPSUITS` AS `DRESSES_AND_JUMPSUITS`
  FROM s0
),
s2 AS (
  SELECT * EXCEPT (`LIVED_AND_LOVED`), `LIVED_AND_LOVED` AS `LIVED_AND_LOVED`
  FROM s1
),
s3 AS (
  SELECT * EXCEPT (`OTHER_3RD_PARTY`), `OTHER_3RD_PARTY` AS `OTHER_3RD_PARTY`
  FROM s2
),
s4 AS (
  SELECT * EXCEPT (`BAGS`), `BAGS` AS `CAT_BAGS`
  FROM s3
),
s5 AS (
  SELECT * EXCEPT (`BASE_LAYERS`), `BASE_LAYERS` AS `CAT_BASE_LAYERS`
  FROM s4
),
s6 AS (
  SELECT * EXCEPT (`BEACH`), `BEACH` AS `CAT_BEACH`
  FROM s5
),
s7 AS (
  SELECT * EXCEPT (`DELIVERY`), `DELIVERY` AS `CAT_DELIVERY`
  FROM s6
),
s8 AS (
  SELECT * EXCEPT (`DRESSES_AND_JUMPSUITS`), `DRESSES_AND_JUMPSUITS` AS `CAT_DRESSES_AND_JUMPSUITS`
  FROM s7
),
s9 AS (
  SELECT * EXCEPT (`FABRIC`), `FABRIC` AS `CAT_FABRIC`
  FROM s8
),
s10 AS (
  SELECT * EXCEPT (`FLEECE`), `FLEECE` AS `CAT_FLEECE`
  FROM s9
),
s11 AS (
  SELECT * EXCEPT (`FOOTWEAR`), `FOOTWEAR` AS `CAT_FOOTWEAR`
  FROM s10
),
s12 AS (
  SELECT * EXCEPT (`GEAR`), `GEAR` AS `CAT_GEAR`
  FROM s11
),
s13 AS (
  SELECT * EXCEPT (`HATS`), `HATS` AS `CAT_HATS`
  FROM s12
),
s14 AS (
  SELECT * EXCEPT (`INSULATION`), `INSULATION` AS `CAT_INSULATION`
  FROM s13
),
s15 AS (
  SELECT * EXCEPT (`JACKETS`), `JACKETS` AS `CAT_JACKETS`
  FROM s14
),
s16 AS (
  SELECT * EXCEPT (`KNITWEAR`), `KNITWEAR` AS `CAT_KNITWEAR`
  FROM s15
),
s17 AS (
  SELECT * EXCEPT (`LEGWEAR`), `LEGWEAR` AS `CAT_LEGWEAR`
  FROM s16
),
s18 AS (
  SELECT * EXCEPT (`LITERATURE`), `LITERATURE` AS `CAT_LITERATURE`
  FROM s17
),
s19 AS (
  SELECT * EXCEPT (`LIVED_AND_LOVED`), `LIVED_AND_LOVED` AS `CAT_LIVED_AND_LOVED`
  FROM s18
),
s20 AS (
  SELECT * EXCEPT (`OTHER`), `OTHER` AS `CAT_OTHER`
  FROM s19
),
s21 AS (
  SELECT * EXCEPT (`OTHER_3RD_PARTY`), `OTHER_3RD_PARTY` AS `CAT_OTHER_3RD_PARTY`
  FROM s20
),
s22 AS (
  SELECT * EXCEPT (`REPAIRS`), `REPAIRS` AS `CAT_REPAIRS`
  FROM s21
),
s23 AS (
  SELECT * EXCEPT (`SHIRTS`), `SHIRTS` AS `CAT_SHIRTS`
  FROM s22
),
s24 AS (
  SELECT * EXCEPT (`SOCKS`), `SOCKS` AS `CAT_SOCKS`
  FROM s23
),
s25 AS (
  SELECT * EXCEPT (`STICKERS`), `STICKERS` AS `CAT_STICKERS`
  FROM s24
),
s26 AS (
  SELECT * EXCEPT (`SWEATS`), `SWEATS` AS `CAT_SWEATS`
  FROM s25
),
s27 AS (
  SELECT * EXCEPT (`TEES`), `TEES` AS `CAT_TEES`
  FROM s26
),
s28 AS (
  SELECT * EXCEPT (`TOPS`), `TOPS` AS `CAT_TOPS`
  FROM s27
),
s29 AS (
  SELECT * EXCEPT (`UNDERWEAR`), `UNDERWEAR` AS `CAT_UNDERWEAR`
  FROM s28
),
s30 AS (
  SELECT * EXCEPT (`WETSUIT`), `WETSUIT` AS `CAT_WETSUIT`
  FROM s29
),
s31 AS (
  SELECT * EXCEPT (`CAT_BAGS`), `CAT_BAGS` AS `CAT_BAGS_DEMAND`
  FROM s30
),
s32 AS (
  SELECT * EXCEPT (`CAT_BASE_LAYERS`), `CAT_BASE_LAYERS` AS `CAT_BASE_LAYERS_DEMAND`
  FROM s31
),
s33 AS (
  SELECT * EXCEPT (`CAT_BEACH`), `CAT_BEACH` AS `CAT_BEACH_DEMAND`
  FROM s32
),
s34 AS (
  SELECT * EXCEPT (`CAT_DELIVERY`), `CAT_DELIVERY` AS `CAT_DELIVERY_DEMAND`
  FROM s33
),
s35 AS (
  SELECT * EXCEPT (`CAT_DRESSES_AND_JUMPSUITS`), `CAT_DRESSES_AND_JUMPSUITS` AS `CAT_DRESSES_AND_JUMPSUITS_DEMAND`
  FROM s34
),
s36 AS (
  SELECT * EXCEPT (`CAT_FABRIC`), `CAT_FABRIC` AS `CAT_FABRIC_DEMAND`
  FROM s35
),
s37 AS (
  SELECT * EXCEPT (`CAT_FLEECE`), `CAT_FLEECE` AS `CAT_FLEECE_DEMAND`
  FROM s36
),
s38 AS (
  SELECT * EXCEPT (`CAT_FOOTWEAR`), `CAT_FOOTWEAR` AS `CAT_FOOTWEAR_DEMAND`
  FROM s37
),
s39 AS (
  SELECT * EXCEPT (`CAT_GEAR`), `CAT_GEAR` AS `CAT_GEAR_DEMAND`
  FROM s38
),
s40 AS (
  SELECT * EXCEPT (`CAT_HATS`), `CAT_HATS` AS `CAT_HATS_DEMAND`
  FROM s39
),
s41 AS (
  SELECT * EXCEPT (`CAT_INSULATION`), `CAT_INSULATION` AS `CAT_INSULATION_DEMAND`
  FROM s40
),
s42 AS (
  SELECT * EXCEPT (`CAT_JACKETS`), `CAT_JACKETS` AS `CAT_JACKETS_DEMAND`
  FROM s41
),
s43 AS (
  SELECT * EXCEPT (`CAT_KNITWEAR`), `CAT_KNITWEAR` AS `CAT_KNITWEAR_DEMAND`
  FROM s42
),
s44 AS (
  SELECT * EXCEPT (`CAT_LEGWEAR`), `CAT_LEGWEAR` AS `CAT_LEGWEAR_DEMAND`
  FROM s43
),
s45 AS (
  SELECT * EXCEPT (`CAT_LITERATURE`), `CAT_LITERATURE` AS `CAT_LITERATURE_DEMAND`
  FROM s44
),
s46 AS (
  SELECT * EXCEPT (`CAT_LIVED_AND_LOVED`), `CAT_LIVED_AND_LOVED` AS `CAT_LIVED_AND_LOVED_DEMAND`
  FROM s45
),
s47 AS (
  SELECT * EXCEPT (`CAT_OTHER`), `CAT_OTHER` AS `CAT_OTHER_DEMAND`
  FROM s46
),
s48 AS (
  SELECT * EXCEPT (`CAT_OTHER_3RD_PARTY`), `CAT_OTHER_3RD_PARTY` AS `CAT_OTHER_3RD_PARTY_DEMAND`
  FROM s47
),
s49 AS (
  SELECT * EXCEPT (`CAT_REPAIRS`), `CAT_REPAIRS` AS `CAT_REPAIRS_DEMAND`
  FROM s48
),
s50 AS (
  SELECT * EXCEPT (`CAT_SHIRTS`), `CAT_SHIRTS` AS `CAT_SHIRTS_DEMAND`
  FROM s49
),
s51 AS (
  SELECT * EXCEPT (`CAT_SOCKS`), `CAT_SOCKS` AS `CAT_SOCKS_DEMAND`
  FROM s50
),
s52 AS (
  SELECT * EXCEPT (`CAT_STICKERS`), `CAT_STICKERS` AS `CAT_STICKERS_DEMAND`
  FROM s51
),
s53 AS (
  SELECT * EXCEPT (`CAT_SWEATS`), `CAT_SWEATS` AS `CAT_SWEATS_DEMAND`
  FROM s52
),
s54 AS (
  SELECT * EXCEPT (`CAT_TEES`), `CAT_TEES` AS `CAT_TEES_DEMAND`
  FROM s53
),
s55 AS (
  SELECT * EXCEPT (`CAT_TOPS`), `CAT_TOPS` AS `CAT_TOPS_DEMAND`
  FROM s54
),
s56 AS (
  SELECT * EXCEPT (`CAT_UNDERWEAR`), `CAT_UNDERWEAR` AS `CAT_UNDERWEAR_DEMAND`
  FROM s55
),
s57 AS (
  SELECT * EXCEPT (`CAT_WETSUIT`), `CAT_WETSUIT` AS `CAT_WETSUIT_DEMAND`
  FROM s56
),
s58 AS (
  SELECT * EXCEPT (`CUSTOMER_ID`), `CUSTOMER_ID` AS `CUSTOMER_ID_REM`
  FROM s57
)
SELECT * FROM s58
