WITH
s0 AS (
  SELECT *,
    CAST(REGEXP_EXTRACT(`FULL_MERCH_FY_MONTH`, 'P(\d+)') AS INT64) AS `FY_PERIOD_NUM`
  FROM `discount`
),
s1 AS (
  SELECT *,
    CASE
  WHEN `FY_PERIOD_NUM` = 1 OR `FY_PERIOD_NUM` = 2 OR `FY_PERIOD_NUM` = 3 THEN `AMOUNT_PAID_EXCL_TAX`
  ELSE 0
  END AS `FY_Q1_DEMAND`
  FROM s0
),
s2 AS (
  SELECT *,
    CASE
  WHEN `FY_PERIOD_NUM` = 4 OR `FY_PERIOD_NUM` = 5 OR `FY_PERIOD_NUM` = 6 THEN `AMOUNT_PAID_EXCL_TAX`
  ELSE 0
  END AS `FY_Q2_DEMAND`
  FROM s1
),
s3 AS (
  SELECT *,
    CASE
  WHEN `FY_PERIOD_NUM` = 7 OR `FY_PERIOD_NUM` = 8 OR `FY_PERIOD_NUM` = 9 THEN `AMOUNT_PAID_EXCL_TAX`
  ELSE 0
  END AS `FY_Q3_DEMAND`
  FROM s2
),
s4 AS (
  SELECT *,
    CASE
  WHEN `FY_PERIOD_NUM` = 10 OR `FY_PERIOD_NUM` = 11 OR `FY_PERIOD_NUM` = 12 THEN `AMOUNT_PAID_EXCL_TAX`
  ELSE 0
  END AS `FY_Q4_DEMAND`
  FROM s3
),
s5 AS (
  SELECT *,
    CASE
  WHEN `FY_PERIOD_NUM` = 1 OR `FY_PERIOD_NUM` = 2 OR `FY_PERIOD_NUM` = 3 THEN `DISCOUNT_AMOUNT`
  ELSE 0
  END AS `FY_Q1_DISCOUNT`
  FROM s4
),
s6 AS (
  SELECT *,
    CASE
  WHEN `FY_PERIOD_NUM` = 4 OR `FY_PERIOD_NUM` = 5 OR `FY_PERIOD_NUM` = 6 THEN `DISCOUNT_AMOUNT`
  ELSE 0
  END AS `FY_Q2_DISCOUNT`
  FROM s5
),
s7 AS (
  SELECT *,
    CASE
  WHEN `FY_PERIOD_NUM` = 7 OR `FY_PERIOD_NUM` = 8 OR `FY_PERIOD_NUM` = 9 THEN `DISCOUNT_AMOUNT`
  ELSE 0
  END AS `FY_Q3_DISCOUNT`
  FROM s6
),
s8 AS (
  SELECT *,
    CASE
  WHEN `FY_PERIOD_NUM` = 10 OR `FY_PERIOD_NUM` = 11 OR `FY_PERIOD_NUM` = 12 THEN `DISCOUNT_AMOUNT`
  ELSE 0
  END AS `FY_Q4_DISCOUNT`
  FROM s7
)
SELECT * FROM s8
