WITH
jl0 AS (
  SELECT * EXCEPT (`DAYS_SINCE_PREVIOUS_ORDER`), `DAYS_SINCE_PREVIOUS_ORDER` AS `AVG_DAYS_BETWEEN_ORDERS`
  FROM `avg_and_std`
),
jl1 AS (
  SELECT * EXCEPT (`DAYS_SINCE_PREVIOUS_ORDER_1`), `DAYS_SINCE_PREVIOUS_ORDER_1` AS `STD_DAYS_BETWEEN_ORDERS`
  FROM jl0
),
core AS (
  SELECT
    l.*,
    r.* EXCEPT (`CUSTOMER_ID`)
  FROM jl1 AS l
  RIGHT JOIN `aggregating` AS r
    ON l.`CUSTOMER_ID_REM` = r.`CUSTOMER_ID`
),
jpost0 AS (
  SELECT * EXCEPT (`CUSTOMER_ID_REM`)
  FROM core
)
SELECT * FROM jpost0
