WITH
jl0 AS (
  SELECT * EXCEPT (`CATEGORY_FLAG`), `CATEGORY_FLAG` AS `DISTINCT_CATEGORIES_PURCHASED`
  FROM `cat_count`
),
core AS (
  SELECT
    l.*,
    r.* EXCEPT (`CUSTOMER_ID`)
  FROM jl0 AS l
  RIGHT JOIN `add_cat_demand` AS r
    ON l.`CUSTOMER_ID_REM` = r.`CUSTOMER_ID`
),
jpost0 AS (
  SELECT * EXCEPT (`CUSTOMER_ID_REM`)
  FROM core
)
SELECT * FROM jpost0
