WITH
s0 AS (
  SELECT *,
    `MONETARY_52W` / `FREQUENCY_52W` AS `AOV_52W`
  FROM `join_8`
),
s1 AS (
  SELECT *,
    `MONETARY_104W` / `FREQUENCY_104W` AS `AOV_104W`
  FROM s0
),
s2 AS (
  SELECT *,
    `MONETARY_156W` / `FREQUENCY_156W` AS `AOV_156W`
  FROM s1
),
s3 AS (
  SELECT *,
    `MONETARY_208W` / `FREQUENCY_208W` AS `AOV_208W`
  FROM s2
),
s4 AS (
  SELECT *,
    `MONETARY_260W` / `FREQUENCY_260W` AS `AOV_260W`
  FROM s3
),
s5 AS (
  SELECT * EXCEPT (`ORDER_ID`), `ORDER_ID` AS `TOTAL_LIFETIME_ORDERS`
  FROM s4
),
s6 AS (
  SELECT * EXCEPT (`AMOUNT_REFUNDED_EXCL_TAX`), `AMOUNT_REFUNDED_EXCL_TAX` AS `TOTAL_LIFETIME_RETURNS`
  FROM s5
),
s7 AS (
  SELECT * EXCEPT (`DISCOUNT_AMOUNT`), `DISCOUNT_AMOUNT` AS `TOTAL_LIFETIME_DISCOUNT`
  FROM s6
),
s8 AS (
  SELECT * EXCEPT (`AMOUNT_PAID_EXCL_TAX`), `AMOUNT_PAID_EXCL_TAX` AS `TOTAL_LIFETIME_DEMAND`
  FROM s7
)
SELECT * FROM s8
