WITH
s0 AS (
  SELECT *,
    `DISCOUNT_52W` / (`MONETARY_52W` + `DISCOUNT_52W`) AS `DISCOUNT_PCT_52W`
  FROM `aov`
),
s1 AS (
  SELECT *,
    `DISCOUNT_104W` / (`MONETARY_104W` + `DISCOUNT_104W`) AS `DISCOUNT_PCT_104W`
  FROM s0
),
s2 AS (
  SELECT *,
    `DISCOUNT_156W` / (`MONETARY_156W` + `DISCOUNT_156W`) AS `DISCOUNT_PCT_156W`
  FROM s1
),
s3 AS (
  SELECT *,
    `DISCOUNT_208W` / (`MONETARY_208W` + `DISCOUNT_208W`) AS `DISCOUNT_PCT_208W`
  FROM s2
),
s4 AS (
  SELECT *,
    `DISCOUNT_260W` / (`MONETARY_260W` + `DISCOUNT_260W`) AS `DISCOUNT_PCT_260W`
  FROM s3
),
s5 AS (
  SELECT *,
    `TOTAL_LIFETIME_DISCOUNT` / (`TOTAL_LIFETIME_DEMAND` + `TOTAL_LIFETIME_DISCOUNT`) AS `TOTAL_LIFETIME_DISCOUNT_PCT`
  FROM s4
)
SELECT * FROM s5
