WITH
s0 AS (
  SELECT *,
    CASE
  WHEN COALESCE(`TOTAL_LIFETIME_DEMAND`, 0) = 0 THEN 0
  ELSE `TOTAL_ONLINE_DEMAND` / `TOTAL_LIFETIME_DEMAND`
  END AS `ONLINE_RATIO`
  FROM `discount`
),
s1 AS (
  SELECT *,
    CASE
  WHEN COALESCE(`TOTAL_LIFETIME_DEMAND`, 0) = 0 THEN 0
  ELSE `TOTAL_FULL_PRICE_DEMAND` / `TOTAL_LIFETIME_DEMAND`
  END AS `FULL_PRICE_RATIO`
  FROM s0
),
s2 AS (
  SELECT *,
    CASE
  WHEN COALESCE(`TOTAL_LIFETIME_DEMAND`, 0) = 0 THEN 0
  ELSE `TOTAL_MARKDOWN_DEMAND` / `TOTAL_LIFETIME_DEMAND`
  END AS `MARKDOWN_RATIO`
  FROM s1
),
s3 AS (
  SELECT *,
    CASE
  WHEN `TOTAL_LIFETIME_DEMAND` = 0 THEN 0
  ELSE `TOTAL_LIFETIME_DISCOUNT` / `TOTAL_LIFETIME_DEMAND`
  END AS `DISCOUNT_RATIO`
  FROM s2
),
s4 AS (
  SELECT *,
    `FY_Q1_DEMAND` / `TOTAL_LIFETIME_DEMAND` AS `FY_Q1_DEMAND_RATIO`
  FROM s3
),
s5 AS (
  SELECT *,
    `FY_Q2_DEMAND` / `TOTAL_LIFETIME_DEMAND` AS `FY_Q2_DEMAND_RATIO`
  FROM s4
),
s6 AS (
  SELECT *,
    `FY_Q3_DEMAND` / `TOTAL_LIFETIME_DEMAND` AS `FY_Q3_DEMAND_RATIO`
  FROM s5
),
s7 AS (
  SELECT *,
    `FY_Q4_DEMAND` / `TOTAL_LIFETIME_DEMAND` AS `FY_Q4_DEMAND_RATIO`
  FROM s6
)
SELECT * FROM s7
